// Group codes used for authorization (must match settings.groups.code values)
const GROUPS = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  PRINCIPAL: 'PRINCIPAL',
  TEACHER: 'TEACHER',
  ACCOUNTANT: 'ACCOUNTANT',
  STUDENT: 'STUDENT',
  PARENT: 'PARENT',
};

const ADMIN_ROLES = [GROUPS.SUPER_ADMIN, GROUPS.ADMIN];
const STAFF_ROLES = [GROUPS.SUPER_ADMIN, GROUPS.ADMIN, GROUPS.PRINCIPAL, GROUPS.TEACHER, GROUPS.ACCOUNTANT];

module.exports = { GROUPS, ADMIN_ROLES, STAFF_ROLES, ROLES: GROUPS };
